src/storeroom/inventory/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.index_view, name="index_view"),
    path("capture_data", views.capture_data, name="capture_data"),
    path("inventory_view", views.Inventory_view.as_view(), name="inventory_view"),
    path("inventory_start", views.InventoryStart.as_view(), name="inventory_start"),
    path(
        "inventory_update/<pk>/",
        views.Inventory_update.as_view(),
        name="inventory_update",
    ),
    path("part_view", views.Part_view.as_view(), name="part_view"),
    path("part_control/<pk>/", views.Part_control_view.as_view(), name="part_control"),
    path("purchase_orders", views.Purchase_orders.as_view(), name="purchase_orders"),
    path("new_order", views.New_order.as_view(), name="new_order"),
]

src/storeroom/storeroom/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("inventory.urls")),
]

src/storeroom/inventory/models.py
from django.db import models
from django.db.models.fields import DateField
from django.utils import timezone, dateformat
from django.urls import reverse
from datetime import date


class Inventory(models.Model):
    class Meta:
        db_table = "inventory"
        managed = True

    storage_loc = models.CharField(max_length=12, blank=True, null=True)
    description = models.CharField(max_length=64, blank=True, null=True)
    part = models.CharField(max_length=50, blank=True, null=True)
    vendor = models.CharField(max_length=50, blank=True, null=True)
    in_stock = models.IntegerField(default=0, blank=True, null=True)
    max_stock = models.IntegerField(default=0, blank=True, null=True)
    reorder = models.IntegerField(default=0, blank=True, null=True)
    reorder_amt = models.IntegerField(default=0, blank=True, null=True)
    location = models.CharField(default="DSO", max_length=50, blank=True, null=True)
    inv_date = models.DateField(auto_now=True, null=True)

    def __str__(self):
        return self.id

    def get_absolute_url(self):
        return reverse("inventory_update", kwargs={"pk": self.id})


class Order(models.Model):
    class Meta:
        db_table = "orders"
        managed = True
        ordering = ["-order_date"]

    part = models.ForeignKey(Inventory, on_delete=models.CASCADE)
    order_date = models.DateField(default=date.today(), blank=False)
    receive_date = models.DateField(default=date.today(), blank=False)
    invoice = models.CharField(max_length=64, default="", blank=True, null=True)
    quantity = models.IntegerField(default=1, blank=True, null=True)
    cost = models.IntegerField(default=1, blank=True, null=True)
    tax = models.IntegerField(default=1, blank=True, null=True)
    shipping = models.IntegerField(default=1, blank=True, null=True)
    total = models.IntegerField(default=0, blank=True, null=True)

    def __str__(self):
        return self.id

    def get_absolute_url(self):
        return reverse("purchase_orders", kwargs={"pk": self.id})

src/storeroom/inventory/forms.py
from django.db.models import fields
from django.forms import widgets
from .models import Inventory, Order
from django import forms


class StartForm(forms.ModelForm):
    class Meta:
        model = Inventory
        fields = (
            "part",
            "storage_loc",
        )

    part = forms.CharField(widget=forms.TextInput(attrs={}))
    storage_loc = forms.CharField(widget=forms.TextInput(attrs={}))


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = (
            "order_date",
            "receive_date",
            "invoice",
            "part",
            "quantity",
            "cost",
            "tax",
            "shipping",
            "total",
        )

    order_date = forms.DateField(widget=forms.DateInput(attrs={}))
    receive_date = forms.DateField(required=False, widget=forms.DateInput(attrs={}))
    invoice = forms.CharField(required=False, widget=forms.TextInput(attrs={}))
    part = forms.CharField(widget=forms.TextInput(attrs={}))
    quantity = forms.CharField(widget=forms.TextInput(attrs={}))
    cost = forms.CharField(widget=forms.TextInput(attrs={}))
    tax = forms.CharField(required=False, widget=forms.TextInput(attrs={}))
    shipping = forms.CharField(required=False, widget=forms.TextInput(attrs={}))
    total = forms.CharField(widget=forms.TextInput(attrs={}))


class InventoryUpdateForm(forms.ModelForm):
    class Meta:
        model = Inventory
        fields = (
            "description",
            "part",
            "in_stock",
        )

    # def __init__(self, *args, **kwargs):
    #     super(InventoryUpdateForm, self).__init__(*args, **kwargs)
    #     readonly = [
    #         "description",
    #         "part",
    #     ]
    #     for field in readonly:
    #         self.fields[field].widget.attrs["readonly"] = "true"

    description = forms.CharField(
        widget=forms.Textarea(
            attrs={
                "rows": 3,
                "cols": 24,
                "style": "vertical-align: middle;",
                "readonly": "True",
            }
        )
    )
    part = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "readonly": "True",
            }
        )
    )
    in_stock = forms.CharField(widget=forms.TextInput(attrs={}))

src/storeroom/inventory/views.py
from django.http.response import HttpResponseRedirect
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import F
from django.shortcuts import render, redirect
from django.urls.base import reverse_lazy
from django.views.generic import UpdateView, ListView, FormView, DetailView, CreateView
from django.contrib import messages
from inventory.forms import InventoryUpdateForm, StartForm, OrderForm
from inventory.models import Inventory, Order


def index_view(request, *args, **kwargs):
    return render(request, "index.html", {})


def capture_data(request, *arg, **kwargs):
    if request.method == "POST":
        user_entered_loc = request.POST.get("storage_loc", None).upper()
        link = request.POST.get("link", None)
        try:
            item = Inventory.objects.get(storage_loc=user_entered_loc)
            return HttpResponseRedirect(f"/{link}/{item.id}")
        except ObjectDoesNotExist:
            messages.error(request, "Enter a valid part number")
            return HttpResponseRedirect(f"/{link}")


class InventoryStart(FormView):
    model = Inventory
    form_class = StartForm
    template_name = "inventory_start.html"


class Inventory_view(ListView):
    model = Inventory
    template_name = "inventory_view.html"


class Inventory_update(UpdateView):
    model = Inventory
    form_class = InventoryUpdateForm
    template_name = "inventory_update.html"
    success_url = reverse_lazy("inventory_start")


class Part_view(FormView):
    model = Inventory
    form_class = StartForm
    template_name = "part_view.html"


class Part_control_view(DetailView):
    model = Inventory
    template_name = "part_control.html"

    def post(self, request, *args, **kwargs):
        amount = self.request.POST.get("number")
        item = self.request.POST.get("item")
        change = self.request.POST.get("change")
        obj = Inventory.objects.get(storage_loc=item)
        if change == "add":
            obj.in_stock = F("in_stock") + amount
            obj.save()
        elif change == "remove":
            obj.in_stock = F("in_stock") - amount
            obj.save()
        return redirect(f"/part_control/{obj.id}")


class Purchase_orders(ListView):
    model = Order
    template_name = "purchase_orders.html"


class New_order(CreateView):
    model = Order
    form_class = OrderForm
    template_name = "new_order.html"
    success_url = reverse_lazy("purchase_orders.html")

src/storeroom/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    {% load static %}
    <meta charset="utf-8" />
    {% block head %}{% endblock %}
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Storeroom</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{% static 'styles.css' %}" />
  </head>
  <header class="headWrapper">
    <div>
      <h1>STOREROOM INVENTORY</h1>
    </div>
  </header>
  <div class="divider">
    <div class="divider fade"></div>
  </div>
  <body>
    {%block body%}{%endblock%}
  </body>
</html>

src/storeroom/templates/index.html
{% extends "base.html" %} {% block body %}
<div class="main-button">
  <a href="{% url 'part_view' %}"><button>ADD/REMOVE ITEMS</button></a>
  <a href="{% url 'inventory_start' %}"><button>START INVENTORY</button></a>
  <!-- <a href="{% url 'inventory_view' %}"><button>SHOW AVAILABLE PARTS</button></a> -->
  <a href="{% url 'purchase_orders' %}"><button>PART ORDERS</button></a>
</div>
{% endblock %}

src/storeroom/templates/inventory_start.html
{% extends "base.html" %} {% block body %} {% load static %}

<div class="form-control">
  <form action="capture_data" method="POST" name="start">
    {%csrf_token%} {{form.non_field_errors}}
    <div>
      {{form.subject.errors}}
      <label for="storage_loc">SCAN OR TYPE THE STORAGE LOCATION</label>
      <br /><br />
      {{form.storage_loc}}
    </div>
    <div>
      <input type="hidden" name="link" value="inventory_update" />
    </div>
    <br />
    {% for message in messages %}
    <div class="alert">{{ message }}</div>
    {% endfor %}
    <div><button type="submit">ENTER</button></div>
  </form>
</div>

<div class="home">
  <a href="{% url 'index_view' %}">Home</a>
</div>

<script src="{% static 'js/jquery-3.6.0-min.js' %}"></script>
<script type="text/javascript">
  $(function () {
    $("input#id_storage_loc").focus();
  });
</script>

{% endblock %}

src/storeroom/templates/inventory_update.html
{% extends "base.html" %}

{% block body %} 
<div class="form-control-update">
    <form action="" method = "POST" >
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div>
            {{ form.subject.errors }}
            <label for="description">DESCRIPTION</label>
            {{form.description}}
        </div><br>
        <div>
            {{ form.subject.errors }}
            <label for="part number">PART NUMBER</label>
            {{form.part}}
        </div><br>
        <div>
            {{ form.subject.errors }}
            <label for="stock">IN STOCK</label>
            {{form.in_stock}}
        </div><br>
        <div class = 'form-control-update button'><button type="submit">ENTER</button></div>
    </form>
</div>
<div class="home">
    <a href="{% url 'index_view' %}">Home</a>
  </div>
{% load static %}
<script src="{% static 'js/jquery-3.6.0-min.js' %}"></script>
<script type = 'text/javascript'>
    $(function() {
        //when the page has finished loading, autofocus on the part field
        $('input#id_in_stock').focus();
    });
</script>
{% endblock %} 

src/storeroom/templates/inventory_view.html
{% extends "base.html" %} {% load static %} {% block body %}
<div class="table-control">
  <table>
    <tr>
      <th>STORAGE</th>
      <th>DESCRIPTION</th>
      <th>PART NUMBER</th>
      <th>VENDOR</th>
      <th>ON HAND</th>
      <th>MAX INVENTORY</th>
      <th>REORDER POINT</th>
      <th>REORDER AMOUNT</th>
      <th>LOCATION</th>
      <th>LAST UPDATE</th>
    </tr>
    <tr>
      {% for Inventory in object_list %}
      <td>{{Inventory.storage_loc}}</td>
      <td style="text-align: left">{{Inventory.description}}</td>
      <td style="text-align: left">{{Inventory.part}}</td>
      <td style="text-align: left">{{Inventory.vendor}}</td>
      <td>{{Inventory.in_stock}}</td>
      <td>{{Inventory.max_stock}}</td>
      <td>{{Inventory.reorder}}</td>
      <td>{{Inventory.reorder_amt}}</td>
      <td>{{Inventory.location}}</td>
      <td>{{Inventory.inv_date}}</td>
    </tr>
    {% endfor %}
  </table>
</div>
<div class="home">
  <a href="{% url 'index_view' %}">Home</a>
</div>

{% endblock %}

src/storeroom/templates/new_order.html
{% extends 'base.html' %} {% block body %} {% load static %}

  <!-- <div class="form-control-update">
    <form action="" method = "POST" >
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div>
            {{ form.subject.errors }}
            <label for="form_date">DATE</label>
            {{form.form_date}}
        </div><br>
        <div>
            {{ form.subject.errors }}
            <label for="receive_date">RECEIVED</label>
            {{form.receive_date}}
        </div><br>
        <div>
            {{ form.subject.errors }}
            <label for="purchaser">PURCHASER</label>
            {{form.purchaser}}
        </div><br>
        <div>
          {{ form.subject.errors }}
          <label for="quote">QUOTE</label>
          {{form.quote}}
        </div><br>
        <div>
          {{ form.subject.errors }}
         <label for="PO">PO</label>
          {{form.PO}}
        </div><br>
        <div>
          {{ form.subject.errors }}
          <label for="invoice">INVOICE</label>
          {{form.invoice}}
      </div><br>
      <div>
        {{ form.subject.errors }}
        <label for="account_code">ACCOUNT CODE</label>
        {{form.acct_code}}
    </div><br>
    <div>
      {{ form.subject.errors }}
      <label for="part">PART NUMBER</label>
      {{form.part}}
  </div><br>
  <div>
    {{ form.subject.errors }}
    <label for="quantity">QUANTITY</label>
    {{form.quantity}}
  </div><br>
  <div>
    {{ form.subject.errors }}
    <label for="cost">UNIT COST</label>
    {{form.cost}}
  </div><br>
  <div>
    {{ form.subject.errors }}
    <label for="tax">TAX</label>
    {{form.tax}}
  </div><br>
  <div>
    {{ form.subject.errors }}
    <label for="shipping">SHIPPING</label>
    {{form.shipping}}
  </div><br>
  <div>
    {{ form.subject.errors }}
    <label for="total">TOTAL</label>
    {{form.total}}
  </div><br>
  <div>
    {{ form.subject.errors }}
    <label for="reason">PURPOSE</label>
    {{form.reason_code}}
  </div><br>
  <div>
    {{ form.subject.errors }}
    <label for="reconcile">RECONCILED</label>
    {{form.reconcile_date}}
  </div><br>
        <div class = 'form-control-update button'><button type="submit">ENTER</button></div>
    </form>
</div> -->
  <table>
    <form action="" method = "POST" >
      {% csrf_token %}
      {{ form.non_field_errors }}
    <tr>
      <th>ORDER DATE</th>
      <th>RECEIVED</th>
      <th>INVOICE</th>

      </tr>
      <tr>
        <td>{{ form.subject.errors }} {{form.order_date}}</td>
        <td>{{ form.subject.errors }} {{form.receive_date}}</td>
        <td>{{ form.subject.errors }} {{form.invoice}}</td>

        </tr><br>
    <tr>
      <th>PART NUMBER</th>
      <th>QUANTITY</th>
      <th>UNIT COST</th>
      <th>TAX</th>
      <th>SHIPPING</th>
      <th>TOTAL</th>

    </tr>
    <tr>
      <td>{{ form.subject.errors }} {{form.part}}</td>
      <td>{{ form.subject.errors }} {{form.quantity}}</td>
      <td>{{ form.subject.errors }} {{form.cost}}</td>
      <td>{{ form.subject.errors }} {{form.tax}}</td>
      <td>{{ form.subject.errors }} {{form.shipping}}</td>
      <td>{{ form.subject.errors }} {{form.total}}</td>
    </tr>
   </table>
</div>
<div class="form-control-update button">
  <button type="submit" name="save_order" value="save_order">SAVE</button>
</div>
</form>
<div class="home">
  <a href="{% url 'index_view' %}">Home</a>
</div>


{% endblock %}

src/storeroom/templates/part_control.html
{% extends "base.html" %} {% block body %}{% load static %}
<div class="form-control-update">
  <div>
    <p><strong>STORAGE LOCATION: </strong>{{object.storage_loc}}</p>
  </div>
  <div>
    <p><strong>DESCRIPTION: </strong>{{object.description}}</p>
  </div>
  <div>
    <p><strong>PART NUMBER: </strong>{{object.part}}</p>
  </div>
  <div>
    <p><strong>IN STOCK: </strong>{{object.in_stock}}</p>
  </div>
  <br />
  <form action="" method="POST" name="adjustment">
    {% csrf_token %}
    <div>
      <label for="number">QUANTITY</label
      ><input type="text" name="number" id="number" />
    </div>
    <div>
      <input type="hidden" name="item" value="{{object.storage_loc}}" />
    </div>
    <br />
    <div class="form-control-update button">
      <button type="submit" name="change" value="add">ADD</button><br />
      <button type="submit" name="change" value="remove">REMOVE</button>
    </div>
  </form>
</div>
<div class="home">
  <a href="{% url 'index_view' %}">Home</a>
</div>
{% load static %}
<script src="{% static 'js/jquery-3.6.0-min.js' %}"></script>
<script type="text/javascript">
  $(function () {
    //when the page has finished loading, autofocus on the number field
    $("input#id_number").focus();
  });
</script>
{% endblock %}

src/storeroom/templates/part_view.html
{% extends "base.html" %} {% block body %} {% load static %}

<div class="form-control">
  <form action="capture_data" method="POST" name="start">
    {%csrf_token%} {{form.non_field_errors}}
    <div>
      {{form.subject.errors}}
      <label for="storage_loc">SCAN OR TYPE THE STORAGE LOCATION</label
      ><br /><br />
      {{form.storage_loc}}
    </div>
    <div>
      <input type="hidden" name="link" value="part_control" />
    </div>
    <br />
    {% for message in messages %}
    <div class="alert">{{ message }}</div>
    {% endfor %}
    <div><button type="submit">ENTER</button></div>
  </form>
</div>

<div class="home">
  <a href="{% url 'index_view' %}">Home</a>
</div>

<script src="{% static 'js/jquery-3.6.0-min.js' %}"></script>
<script type="text/javascript">
  $(function () {
    $("input#id_storage_loc").focus();
  });
</script>

{% endblock %}

src/storeroom/templates/purchase_orders.html
{% extends 'base.html' %} {% block body %} {% load static %}
<div class="table-control">
  <table>
    <tr>
      <th>ORDER DATE</th>
      <th>RECEIVED</th>
      <th>INVOICE</th>
      <th>PART NUMBER</th>
      <th>QUANTITY</th>
      <th>UNIT COST</th>
      <th>TAX</th>
      <th>SHIPPING</th>
      <th>TOTAL</th>
    </tr>
    <tr>
      {% for Order in object_list %}
      <td>{{Order.order_date}}</td>
      <td>{{Order.receive_date}}</td>
      <td>{{Order.invoice}}</td>
      <td>{{Order.part}}</td>
      <td>{{Order.quantity}}</td>
      <td>{{Order.cost}}</td>
      <td>{{Order.tax}}</td>
      <td>{{Order.shipping}}</td>
      <td>{{Order.total}}</td>
    </tr>
    {% endfor %}
  </table>
</div>
<div class="home">
  <a href="{% url 'index_view' %}">Home</a>
  <a href="{% url 'new_order' %}"><button>NEW PURCHASE ORDER</button></a>
</div>

{% endblock %}